[project]
name = "lightweight-project"
version = "0.1.0"
description = "CentOS Stream 10 automation tools"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "yq",
    "pyyaml",
    "click>=8.1.0",
    "ansible",
    "jinja2>=3.1.0,<3.2.0",
    "slack_sdk==3.35.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
